// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Runtime/Events/Uncommitted.proto

package events

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	artifacts "go.dolittle.io/chaostests/contracts/artifacts"
	protobuf "go.dolittle.io/chaostests/contracts/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UncommittedEvent struct {
	Artifact             *artifacts.Artifact  `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	EventSourceId        *protobuf.Uuid       `protobuf:"bytes,2,opt,name=eventSourceId,proto3" json:"eventSourceId,omitempty"`
	Occurred             *timestamp.Timestamp `protobuf:"bytes,3,opt,name=occurred,proto3" json:"occurred,omitempty"`
	Public               bool                 `protobuf:"varint,4,opt,name=public,proto3" json:"public,omitempty"`
	Content              string               `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UncommittedEvent) Reset()         { *m = UncommittedEvent{} }
func (m *UncommittedEvent) String() string { return proto.CompactTextString(m) }
func (*UncommittedEvent) ProtoMessage()    {}
func (*UncommittedEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1881887fc7f3563, []int{0}
}

func (m *UncommittedEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UncommittedEvent.Unmarshal(m, b)
}
func (m *UncommittedEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UncommittedEvent.Marshal(b, m, deterministic)
}
func (m *UncommittedEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UncommittedEvent.Merge(m, src)
}
func (m *UncommittedEvent) XXX_Size() int {
	return xxx_messageInfo_UncommittedEvent.Size(m)
}
func (m *UncommittedEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UncommittedEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UncommittedEvent proto.InternalMessageInfo

func (m *UncommittedEvent) GetArtifact() *artifacts.Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *UncommittedEvent) GetEventSourceId() *protobuf.Uuid {
	if m != nil {
		return m.EventSourceId
	}
	return nil
}

func (m *UncommittedEvent) GetOccurred() *timestamp.Timestamp {
	if m != nil {
		return m.Occurred
	}
	return nil
}

func (m *UncommittedEvent) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *UncommittedEvent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type UncommittedAggregateEvents struct {
	AggregateRootId              *protobuf.Uuid                                          `protobuf:"bytes,1,opt,name=aggregateRootId,proto3" json:"aggregateRootId,omitempty"`
	EventSourceId                *protobuf.Uuid                                          `protobuf:"bytes,2,opt,name=eventSourceId,proto3" json:"eventSourceId,omitempty"`
	ExpectedAggregateRootVersion uint64                                                  `protobuf:"varint,3,opt,name=expectedAggregateRootVersion,proto3" json:"expectedAggregateRootVersion,omitempty"`
	Events                       []*UncommittedAggregateEvents_UncommittedAggregateEvent `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral         struct{}                                                `json:"-"`
	XXX_unrecognized             []byte                                                  `json:"-"`
	XXX_sizecache                int32                                                   `json:"-"`
}

func (m *UncommittedAggregateEvents) Reset()         { *m = UncommittedAggregateEvents{} }
func (m *UncommittedAggregateEvents) String() string { return proto.CompactTextString(m) }
func (*UncommittedAggregateEvents) ProtoMessage()    {}
func (*UncommittedAggregateEvents) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1881887fc7f3563, []int{1}
}

func (m *UncommittedAggregateEvents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UncommittedAggregateEvents.Unmarshal(m, b)
}
func (m *UncommittedAggregateEvents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UncommittedAggregateEvents.Marshal(b, m, deterministic)
}
func (m *UncommittedAggregateEvents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UncommittedAggregateEvents.Merge(m, src)
}
func (m *UncommittedAggregateEvents) XXX_Size() int {
	return xxx_messageInfo_UncommittedAggregateEvents.Size(m)
}
func (m *UncommittedAggregateEvents) XXX_DiscardUnknown() {
	xxx_messageInfo_UncommittedAggregateEvents.DiscardUnknown(m)
}

var xxx_messageInfo_UncommittedAggregateEvents proto.InternalMessageInfo

func (m *UncommittedAggregateEvents) GetAggregateRootId() *protobuf.Uuid {
	if m != nil {
		return m.AggregateRootId
	}
	return nil
}

func (m *UncommittedAggregateEvents) GetEventSourceId() *protobuf.Uuid {
	if m != nil {
		return m.EventSourceId
	}
	return nil
}

func (m *UncommittedAggregateEvents) GetExpectedAggregateRootVersion() uint64 {
	if m != nil {
		return m.ExpectedAggregateRootVersion
	}
	return 0
}

func (m *UncommittedAggregateEvents) GetEvents() []*UncommittedAggregateEvents_UncommittedAggregateEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type UncommittedAggregateEvents_UncommittedAggregateEvent struct {
	Artifact             *artifacts.Artifact  `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	Occurred             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=occurred,proto3" json:"occurred,omitempty"`
	Public               bool                 `protobuf:"varint,3,opt,name=public,proto3" json:"public,omitempty"`
	Content              string               `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) Reset() {
	*m = UncommittedAggregateEvents_UncommittedAggregateEvent{}
}
func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) String() string {
	return proto.CompactTextString(m)
}
func (*UncommittedAggregateEvents_UncommittedAggregateEvent) ProtoMessage() {}
func (*UncommittedAggregateEvents_UncommittedAggregateEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1881887fc7f3563, []int{1, 0}
}

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent.Unmarshal(m, b)
}
func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent.Marshal(b, m, deterministic)
}
func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent.Merge(m, src)
}
func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) XXX_Size() int {
	return xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent.Size(m)
}
func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UncommittedAggregateEvents_UncommittedAggregateEvent proto.InternalMessageInfo

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) GetArtifact() *artifacts.Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) GetOccurred() *timestamp.Timestamp {
	if m != nil {
		return m.Occurred
	}
	return nil
}

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *UncommittedAggregateEvents_UncommittedAggregateEvent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func init() {
	proto.RegisterType((*UncommittedEvent)(nil), "dolittle.runtime.events.UncommittedEvent")
	proto.RegisterType((*UncommittedAggregateEvents)(nil), "dolittle.runtime.events.UncommittedAggregateEvents")
	proto.RegisterType((*UncommittedAggregateEvents_UncommittedAggregateEvent)(nil), "dolittle.runtime.events.UncommittedAggregateEvents.UncommittedAggregateEvent")
}

func init() { proto.RegisterFile("Runtime/Events/Uncommitted.proto", fileDescriptor_b1881887fc7f3563) }

var fileDescriptor_b1881887fc7f3563 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x8b, 0xd4, 0x30,
	0x1c, 0xa5, 0x33, 0x75, 0x1c, 0xb3, 0x88, 0xd2, 0x83, 0x5b, 0xcb, 0x82, 0x75, 0x41, 0x98, 0x53,
	0x02, 0x23, 0x88, 0x17, 0x0f, 0xb3, 0xfe, 0x81, 0x3d, 0x08, 0x12, 0x5d, 0x11, 0x6f, 0x99, 0xf4,
	0xb7, 0x35, 0xd0, 0x26, 0x25, 0xf9, 0x55, 0xfc, 0x0e, 0x7e, 0x13, 0xbf, 0x84, 0x9f, 0xca, 0xbb,
	0x34, 0x4d, 0xe6, 0x8f, 0x50, 0x0f, 0xbb, 0xb7, 0x26, 0x79, 0x2f, 0xbf, 0xf7, 0x5e, 0x5f, 0x48,
	0xc9, 0x7b, 0x8d, 0xaa, 0x05, 0xf6, 0xf6, 0x3b, 0x68, 0x74, 0xec, 0x4a, 0x4b, 0xd3, 0xb6, 0x0a,
	0x11, 0x2a, 0xda, 0x59, 0x83, 0x26, 0x3b, 0xad, 0x4c, 0xa3, 0x10, 0x1b, 0xa0, 0x76, 0x84, 0x52,
	0xf0, 0xd0, 0xe2, 0xd9, 0xbb, 0x5e, 0x57, 0xa2, 0x05, 0x8d, 0xa2, 0x71, 0x6c, 0x63, 0x51, 0x5d,
	0x0b, 0x89, 0xfb, 0xaf, 0x91, 0x5f, 0x94, 0x47, 0xb0, 0x0f, 0xc3, 0xde, 0xb6, 0xbf, 0x66, 0x57,
	0xbd, 0x0a, 0x13, 0x8a, 0x27, 0xb5, 0x31, 0x75, 0x03, 0xac, 0x8b, 0x67, 0xc3, 0x14, 0x87, 0xa2,
	0xed, 0x46, 0xc0, 0xf9, 0x9f, 0x84, 0x3c, 0x3c, 0x10, 0xe6, 0xa5, 0x66, 0x2f, 0xc9, 0x52, 0x84,
	0x49, 0x79, 0x52, 0x26, 0xab, 0x93, 0xf5, 0x19, 0xdd, 0x49, 0x8d, 0x27, 0x8e, 0x46, 0x35, 0x7c,
	0x87, 0xce, 0x5e, 0x91, 0xfb, 0xde, 0xc2, 0x47, 0xd3, 0x5b, 0x09, 0x97, 0x55, 0x3e, 0xf3, 0xf4,
	0xd3, 0x3d, 0x3d, 0x2a, 0xa1, 0x83, 0x4a, 0x7e, 0x8c, 0xce, 0x5e, 0x90, 0xa5, 0x91, 0xb2, 0xb7,
	0x16, 0xaa, 0x7c, 0xee, 0x99, 0x05, 0x1d, 0x1d, 0xec, 0x79, 0x9f, 0xa2, 0x03, 0xbe, 0xc3, 0x66,
	0x8f, 0xc8, 0xa2, 0xeb, 0xb7, 0x8d, 0x92, 0x79, 0x5a, 0x26, 0xab, 0x25, 0x0f, 0xab, 0x2c, 0x27,
	0x77, 0xa5, 0xd1, 0x08, 0x1a, 0xf3, 0x3b, 0x65, 0xb2, 0xba, 0xc7, 0xe3, 0xf2, 0xfc, 0x67, 0x4a,
	0x8a, 0x03, 0xdf, 0x9b, 0xba, 0xb6, 0x50, 0x0b, 0x84, 0xf1, 0x5f, 0x65, 0x1b, 0xf2, 0x40, 0xc4,
	0x2d, 0x6e, 0x0c, 0x5e, 0x56, 0x21, 0x88, 0x49, 0x27, 0xff, 0xe2, 0x6f, 0x1b, 0xc5, 0x05, 0x39,
	0x83, 0x1f, 0x1d, 0xc8, 0x43, 0x71, 0xc3, 0xcd, 0x9f, 0xc1, 0x3a, 0x65, 0xb4, 0x8f, 0x27, 0xe5,
	0xff, 0xc5, 0x64, 0x40, 0x16, 0x63, 0xa1, 0xf2, 0xb4, 0x9c, 0xaf, 0x4e, 0xd6, 0xef, 0xe9, 0x44,
	0xe1, 0xe8, 0x74, 0x14, 0xd3, 0x47, 0x3c, 0x5c, 0x5e, 0xfc, 0x4e, 0xc8, 0xe3, 0x49, 0xd4, 0x2d,
	0xca, 0x74, 0xd8, 0x86, 0xd9, 0x8d, 0xda, 0x30, 0x9f, 0x6a, 0x43, 0x7a, 0xd4, 0x86, 0x8b, 0x2f,
	0x5f, 0xd7, 0xb5, 0xd9, 0xab, 0x52, 0x86, 0xc9, 0x6f, 0xc2, 0x38, 0x04, 0x87, 0x8e, 0x0d, 0x20,
	0xeb, 0x9f, 0x5f, 0x08, 0x8d, 0x8d, 0xbe, 0x7f, 0xcd, 0x9e, 0xbe, 0x89, 0x8c, 0xf0, 0xd4, 0x69,
	0xc8, 0xec, 0x75, 0xa4, 0x6c, 0x17, 0x5e, 0xe9, 0xf3, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcc,
	0x04, 0xa8, 0xfa, 0x0d, 0x04, 0x00, 0x00,
}
