// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Runtime/Events.Processing/Filters.proto

package processing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	protobuf "go.dolittle.io/chaostests/contracts/protobuf"
	services "go.dolittle.io/chaostests/contracts/services"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FiltersRegistrationRequest struct {
	CallContext          *services.ReverseCallArgumentsContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	ScopeId              *protobuf.Uuid                        `protobuf:"bytes,2,opt,name=scopeId,proto3" json:"scopeId,omitempty"`
	FilterId             *protobuf.Uuid                        `protobuf:"bytes,3,opt,name=filterId,proto3" json:"filterId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *FiltersRegistrationRequest) Reset()         { *m = FiltersRegistrationRequest{} }
func (m *FiltersRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*FiltersRegistrationRequest) ProtoMessage()    {}
func (*FiltersRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{0}
}

func (m *FiltersRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FiltersRegistrationRequest.Unmarshal(m, b)
}
func (m *FiltersRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FiltersRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *FiltersRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FiltersRegistrationRequest.Merge(m, src)
}
func (m *FiltersRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_FiltersRegistrationRequest.Size(m)
}
func (m *FiltersRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FiltersRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FiltersRegistrationRequest proto.InternalMessageInfo

func (m *FiltersRegistrationRequest) GetCallContext() *services.ReverseCallArgumentsContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *FiltersRegistrationRequest) GetScopeId() *protobuf.Uuid {
	if m != nil {
		return m.ScopeId
	}
	return nil
}

func (m *FiltersRegistrationRequest) GetFilterId() *protobuf.Uuid {
	if m != nil {
		return m.FilterId
	}
	return nil
}

type FilterResponse struct {
	CallContext          *services.ReverseCallResponseContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	IsIncluded           bool                                 `protobuf:"varint,2,opt,name=isIncluded,proto3" json:"isIncluded,omitempty"`
	PartitionId          *protobuf.Uuid                       `protobuf:"bytes,3,opt,name=partitionId,proto3" json:"partitionId,omitempty"`
	Failure              *ProcessorFailure                    `protobuf:"bytes,4,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *FilterResponse) Reset()         { *m = FilterResponse{} }
func (m *FilterResponse) String() string { return proto.CompactTextString(m) }
func (*FilterResponse) ProtoMessage()    {}
func (*FilterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{1}
}

func (m *FilterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterResponse.Unmarshal(m, b)
}
func (m *FilterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterResponse.Marshal(b, m, deterministic)
}
func (m *FilterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterResponse.Merge(m, src)
}
func (m *FilterResponse) XXX_Size() int {
	return xxx_messageInfo_FilterResponse.Size(m)
}
func (m *FilterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterResponse proto.InternalMessageInfo

func (m *FilterResponse) GetCallContext() *services.ReverseCallResponseContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *FilterResponse) GetIsIncluded() bool {
	if m != nil {
		return m.IsIncluded
	}
	return false
}

func (m *FilterResponse) GetPartitionId() *protobuf.Uuid {
	if m != nil {
		return m.PartitionId
	}
	return nil
}

func (m *FilterResponse) GetFailure() *ProcessorFailure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type FiltersClientToRuntimeMessage struct {
	// Types that are valid to be assigned to Message:
	//	*FiltersClientToRuntimeMessage_RegistrationRequest
	//	*FiltersClientToRuntimeMessage_FilterResult
	Message              isFiltersClientToRuntimeMessage_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}                                `json:"-"`
	XXX_unrecognized     []byte                                  `json:"-"`
	XXX_sizecache        int32                                   `json:"-"`
}

func (m *FiltersClientToRuntimeMessage) Reset()         { *m = FiltersClientToRuntimeMessage{} }
func (m *FiltersClientToRuntimeMessage) String() string { return proto.CompactTextString(m) }
func (*FiltersClientToRuntimeMessage) ProtoMessage()    {}
func (*FiltersClientToRuntimeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{2}
}

func (m *FiltersClientToRuntimeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FiltersClientToRuntimeMessage.Unmarshal(m, b)
}
func (m *FiltersClientToRuntimeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FiltersClientToRuntimeMessage.Marshal(b, m, deterministic)
}
func (m *FiltersClientToRuntimeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FiltersClientToRuntimeMessage.Merge(m, src)
}
func (m *FiltersClientToRuntimeMessage) XXX_Size() int {
	return xxx_messageInfo_FiltersClientToRuntimeMessage.Size(m)
}
func (m *FiltersClientToRuntimeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FiltersClientToRuntimeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FiltersClientToRuntimeMessage proto.InternalMessageInfo

type isFiltersClientToRuntimeMessage_Message interface {
	isFiltersClientToRuntimeMessage_Message()
}

type FiltersClientToRuntimeMessage_RegistrationRequest struct {
	RegistrationRequest *FiltersRegistrationRequest `protobuf:"bytes,1,opt,name=registrationRequest,proto3,oneof"`
}

type FiltersClientToRuntimeMessage_FilterResult struct {
	FilterResult *FilterResponse `protobuf:"bytes,2,opt,name=filterResult,proto3,oneof"`
}

func (*FiltersClientToRuntimeMessage_RegistrationRequest) isFiltersClientToRuntimeMessage_Message() {}

func (*FiltersClientToRuntimeMessage_FilterResult) isFiltersClientToRuntimeMessage_Message() {}

func (m *FiltersClientToRuntimeMessage) GetMessage() isFiltersClientToRuntimeMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *FiltersClientToRuntimeMessage) GetRegistrationRequest() *FiltersRegistrationRequest {
	if x, ok := m.GetMessage().(*FiltersClientToRuntimeMessage_RegistrationRequest); ok {
		return x.RegistrationRequest
	}
	return nil
}

func (m *FiltersClientToRuntimeMessage) GetFilterResult() *FilterResponse {
	if x, ok := m.GetMessage().(*FiltersClientToRuntimeMessage_FilterResult); ok {
		return x.FilterResult
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FiltersClientToRuntimeMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FiltersClientToRuntimeMessage_RegistrationRequest)(nil),
		(*FiltersClientToRuntimeMessage_FilterResult)(nil),
	}
}

type FilterRegistrationResponse struct {
	Failure              *protobuf.Failure `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FilterRegistrationResponse) Reset()         { *m = FilterRegistrationResponse{} }
func (m *FilterRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*FilterRegistrationResponse) ProtoMessage()    {}
func (*FilterRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{3}
}

func (m *FilterRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRegistrationResponse.Unmarshal(m, b)
}
func (m *FilterRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *FilterRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRegistrationResponse.Merge(m, src)
}
func (m *FilterRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_FilterRegistrationResponse.Size(m)
}
func (m *FilterRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRegistrationResponse proto.InternalMessageInfo

func (m *FilterRegistrationResponse) GetFailure() *protobuf.Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type FilterEventRequest struct {
	CallContext          *services.ReverseCallRequestContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	Event                *StreamEvent                        `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	RetryProcessingState *RetryProcessingState               `protobuf:"bytes,3,opt,name=retryProcessingState,proto3" json:"retryProcessingState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *FilterEventRequest) Reset()         { *m = FilterEventRequest{} }
func (m *FilterEventRequest) String() string { return proto.CompactTextString(m) }
func (*FilterEventRequest) ProtoMessage()    {}
func (*FilterEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{4}
}

func (m *FilterEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterEventRequest.Unmarshal(m, b)
}
func (m *FilterEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterEventRequest.Marshal(b, m, deterministic)
}
func (m *FilterEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterEventRequest.Merge(m, src)
}
func (m *FilterEventRequest) XXX_Size() int {
	return xxx_messageInfo_FilterEventRequest.Size(m)
}
func (m *FilterEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FilterEventRequest proto.InternalMessageInfo

func (m *FilterEventRequest) GetCallContext() *services.ReverseCallRequestContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *FilterEventRequest) GetEvent() *StreamEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *FilterEventRequest) GetRetryProcessingState() *RetryProcessingState {
	if m != nil {
		return m.RetryProcessingState
	}
	return nil
}

type FilterRuntimeToClientMessage struct {
	// Types that are valid to be assigned to Message:
	//	*FilterRuntimeToClientMessage_RegistrationResponse
	//	*FilterRuntimeToClientMessage_FilterRequest
	Message              isFilterRuntimeToClientMessage_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *FilterRuntimeToClientMessage) Reset()         { *m = FilterRuntimeToClientMessage{} }
func (m *FilterRuntimeToClientMessage) String() string { return proto.CompactTextString(m) }
func (*FilterRuntimeToClientMessage) ProtoMessage()    {}
func (*FilterRuntimeToClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c76a8c5cdce820f2, []int{5}
}

func (m *FilterRuntimeToClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterRuntimeToClientMessage.Unmarshal(m, b)
}
func (m *FilterRuntimeToClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterRuntimeToClientMessage.Marshal(b, m, deterministic)
}
func (m *FilterRuntimeToClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterRuntimeToClientMessage.Merge(m, src)
}
func (m *FilterRuntimeToClientMessage) XXX_Size() int {
	return xxx_messageInfo_FilterRuntimeToClientMessage.Size(m)
}
func (m *FilterRuntimeToClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterRuntimeToClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FilterRuntimeToClientMessage proto.InternalMessageInfo

type isFilterRuntimeToClientMessage_Message interface {
	isFilterRuntimeToClientMessage_Message()
}

type FilterRuntimeToClientMessage_RegistrationResponse struct {
	RegistrationResponse *FilterRegistrationResponse `protobuf:"bytes,1,opt,name=registrationResponse,proto3,oneof"`
}

type FilterRuntimeToClientMessage_FilterRequest struct {
	FilterRequest *FilterEventRequest `protobuf:"bytes,2,opt,name=filterRequest,proto3,oneof"`
}

func (*FilterRuntimeToClientMessage_RegistrationResponse) isFilterRuntimeToClientMessage_Message() {}

func (*FilterRuntimeToClientMessage_FilterRequest) isFilterRuntimeToClientMessage_Message() {}

func (m *FilterRuntimeToClientMessage) GetMessage() isFilterRuntimeToClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *FilterRuntimeToClientMessage) GetRegistrationResponse() *FilterRegistrationResponse {
	if x, ok := m.GetMessage().(*FilterRuntimeToClientMessage_RegistrationResponse); ok {
		return x.RegistrationResponse
	}
	return nil
}

func (m *FilterRuntimeToClientMessage) GetFilterRequest() *FilterEventRequest {
	if x, ok := m.GetMessage().(*FilterRuntimeToClientMessage_FilterRequest); ok {
		return x.FilterRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*FilterRuntimeToClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*FilterRuntimeToClientMessage_RegistrationResponse)(nil),
		(*FilterRuntimeToClientMessage_FilterRequest)(nil),
	}
}

func init() {
	proto.RegisterType((*FiltersRegistrationRequest)(nil), "dolittle.runtime.events.processing.FiltersRegistrationRequest")
	proto.RegisterType((*FilterResponse)(nil), "dolittle.runtime.events.processing.FilterResponse")
	proto.RegisterType((*FiltersClientToRuntimeMessage)(nil), "dolittle.runtime.events.processing.FiltersClientToRuntimeMessage")
	proto.RegisterType((*FilterRegistrationResponse)(nil), "dolittle.runtime.events.processing.FilterRegistrationResponse")
	proto.RegisterType((*FilterEventRequest)(nil), "dolittle.runtime.events.processing.FilterEventRequest")
	proto.RegisterType((*FilterRuntimeToClientMessage)(nil), "dolittle.runtime.events.processing.FilterRuntimeToClientMessage")
}

func init() {
	proto.RegisterFile("Runtime/Events.Processing/Filters.proto", fileDescriptor_c76a8c5cdce820f2)
}

var fileDescriptor_c76a8c5cdce820f2 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0x41, 0x6f, 0x13, 0x3d,
	0x10, 0xcd, 0xe6, 0xfb, 0x20, 0xc5, 0x05, 0x0e, 0x06, 0x89, 0x28, 0x02, 0x54, 0x85, 0x03, 0x15,
	0x14, 0x2f, 0xb4, 0x15, 0x82, 0x03, 0x88, 0x36, 0xb4, 0x4a, 0x0f, 0x94, 0xca, 0x2d, 0x12, 0xe2,
	0x80, 0xb4, 0xdd, 0x4c, 0x82, 0xa5, 0xad, 0xbd, 0xd8, 0xb3, 0x15, 0xfc, 0x07, 0x4e, 0xdc, 0xb8,
	0xf0, 0x03, 0xf8, 0x41, 0xfc, 0x16, 0x6e, 0xa0, 0xac, 0xed, 0xec, 0x46, 0x71, 0xdb, 0xe4, 0x16,
	0xad, 0xe6, 0xbd, 0x99, 0xf7, 0xe6, 0x8d, 0x43, 0xee, 0xf3, 0x42, 0xa2, 0x38, 0x81, 0x78, 0xe7,
	0x14, 0x24, 0x1a, 0x76, 0xa0, 0x55, 0x0a, 0xc6, 0x08, 0x39, 0x8a, 0x77, 0x45, 0x86, 0xa0, 0x0d,
	0xcb, 0xb5, 0x42, 0x45, 0xbb, 0x03, 0x95, 0x09, 0xc4, 0x0c, 0x98, 0xb6, 0x08, 0x06, 0x16, 0x91,
	0x4f, 0x10, 0x9d, 0x95, 0xdd, 0x42, 0x0e, 0x92, 0x13, 0x90, 0x98, 0x64, 0x26, 0x3e, 0x18, 0xe3,
	0x8e, 0x8b, 0x61, 0xfc, 0xae, 0x10, 0x03, 0xcb, 0xd2, 0xb9, 0x17, 0xae, 0xd8, 0x4d, 0x44, 0x56,
	0x68, 0x70, 0x45, 0x6c, 0xaa, 0xe8, 0x10, 0xf4, 0xa9, 0x48, 0xc1, 0xc4, 0x1c, 0x4e, 0x41, 0x1b,
	0xe8, 0x25, 0x59, 0xd6, 0x53, 0x12, 0xe1, 0x0b, 0xba, 0xfa, 0x87, 0x67, 0x6b, 0x38, 0x44, 0x0d,
	0xc9, 0x49, 0xf9, 0xdd, 0x15, 0x3f, 0x38, 0xbb, 0xd8, 0xfd, 0x54, 0x5e, 0x73, 0xf7, 0x77, 0x44,
	0x3a, 0xce, 0x05, 0x0e, 0x23, 0x61, 0x50, 0x27, 0x28, 0x94, 0xe4, 0xf0, 0xb9, 0x00, 0x83, 0xf4,
	0x80, 0x2c, 0xa7, 0xd5, 0x30, 0xed, 0x68, 0x25, 0x5a, 0x5d, 0x5e, 0x67, 0x6c, 0x62, 0x94, 0x71,
	0x93, 0xb3, 0xda, 0xe4, 0x5b, 0x7a, 0x54, 0x8c, 0x95, 0x19, 0x87, 0xe2, 0x75, 0x0a, 0xfa, 0x84,
	0xb4, 0x4c, 0xaa, 0x72, 0xd8, 0x1b, 0xb4, 0x9b, 0x25, 0xdb, 0xad, 0x8a, 0x2d, 0x77, 0x66, 0xb1,
	0xb1, 0x9d, 0xdc, 0xd7, 0xd1, 0x0d, 0xb2, 0x34, 0x2c, 0x47, 0xdc, 0x1b, 0xb4, 0xff, 0x3b, 0x1f,
	0x33, 0x29, 0xec, 0x7e, 0x6b, 0x92, 0xeb, 0x56, 0x18, 0x07, 0x93, 0x2b, 0x69, 0x80, 0xbe, 0x0d,
	0x89, 0x79, 0x74, 0xbe, 0x18, 0x0f, 0x0e, 0x6a, 0xb9, 0x4b, 0x88, 0x30, 0x7b, 0x32, 0xcd, 0x8a,
	0x01, 0x58, 0x39, 0x4b, 0xbc, 0xf6, 0x85, 0x3e, 0x27, 0xcb, 0x79, 0xa2, 0x51, 0x8c, 0x1d, 0xbd,
	0x78, 0xf6, 0x7a, 0x2d, 0xdd, 0x27, 0xad, 0xa1, 0x4d, 0x4c, 0xfb, 0xff, 0x12, 0xb6, 0xc9, 0x2e,
	0x4e, 0x27, 0x9b, 0xac, 0xd7, 0xa5, 0x8d, 0x7b, 0x92, 0xee, 0x9f, 0x88, 0xdc, 0x71, 0x7b, 0xee,
	0x65, 0x02, 0x24, 0x1e, 0x29, 0x97, 0x92, 0x37, 0x60, 0x4c, 0x32, 0x02, 0xaa, 0xc9, 0x0d, 0x3d,
	0x9b, 0x00, 0xe7, 0xd2, 0xcb, 0x79, 0xba, 0x9f, 0x9d, 0xa3, 0x7e, 0x83, 0x87, 0xc8, 0xe9, 0x7b,
	0x72, 0x75, 0xe8, 0x77, 0x54, 0x64, 0xe8, 0x12, 0xb1, 0x3e, 0x7f, 0x33, 0xbf, 0x9e, 0x7e, 0x83,
	0x4f, 0x31, 0x6d, 0x5f, 0x21, 0x2d, 0x27, 0xac, 0xcb, 0x7d, 0xc2, 0xa7, 0x07, 0x73, 0xa1, 0xd8,
	0xac, 0x8c, 0xb6, 0x52, 0x3b, 0x81, 0xfd, 0xcc, 0xd8, 0xf9, 0xa3, 0x49, 0xa8, 0x25, 0x2d, 0x6f,
	0xcc, 0xeb, 0xd9, 0x0f, 0x25, 0x6c, 0xed, 0xa2, 0x84, 0x95, 0xd8, 0x60, 0xc0, 0x76, 0xc8, 0xa5,
	0x52, 0xb9, 0x33, 0x26, 0x9e, 0xc7, 0x98, 0xda, 0x7b, 0xc0, 0x2d, 0x9a, 0x66, 0xe4, 0xa6, 0x06,
	0xd4, 0x5f, 0xab, 0x87, 0xe0, 0x10, 0x13, 0x04, 0x17, 0xc8, 0x67, 0xf3, 0xb0, 0xf2, 0x00, 0x9e,
	0x07, 0x59, 0xbb, 0x7f, 0x23, 0x72, 0xdb, 0x19, 0x6e, 0xe9, 0x8e, 0x94, 0x8d, 0x9c, 0x4f, 0x1a,
	0x8e, 0xc7, 0x99, 0x5d, 0xc5, 0xe2, 0x51, 0x0b, 0x2d, 0xb4, 0xdf, 0xe0, 0x41, 0x76, 0xfa, 0x91,
	0x5c, 0xf3, 0x09, 0xb1, 0xc9, 0xb6, 0x9e, 0x3e, 0x9d, 0xbf, 0x5d, 0x7d, 0xd5, 0xfd, 0x06, 0x9f,
	0xa6, 0xab, 0x25, 0x6e, 0xfd, 0x67, 0x44, 0x5a, 0xee, 0x18, 0xe8, 0xf7, 0x88, 0xb4, 0x7a, 0x4a,
	0x4a, 0x48, 0x91, 0x6e, 0x2d, 0x70, 0x45, 0xe1, 0x2b, 0xed, 0xbc, 0x5a, 0xc0, 0x9d, 0xa0, 0xfb,
	0xab, 0xd1, 0xe3, 0x68, 0x5b, 0x7e, 0x78, 0x31, 0x52, 0x15, 0x93, 0x50, 0x71, 0xfa, 0x29, 0x51,
	0x06, 0xc1, 0xa0, 0x89, 0x53, 0x25, 0x51, 0x27, 0x29, 0x9a, 0xd8, 0x75, 0x88, 0x6d, 0x87, 0xb8,
	0xea, 0xf0, 0xab, 0xb9, 0xf6, 0xda, 0x83, 0x5d, 0x1b, 0x36, 0xf3, 0x67, 0xc3, 0x7a, 0x9e, 0xe8,
	0xf8, 0x72, 0x79, 0x49, 0x1b, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xf3, 0x12, 0xd8, 0x8b,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FiltersClient is the client API for Filters service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FiltersClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Filters_ConnectClient, error)
}

type filtersClient struct {
	cc *grpc.ClientConn
}

func NewFiltersClient(cc *grpc.ClientConn) FiltersClient {
	return &filtersClient{cc}
}

func (c *filtersClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Filters_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Filters_serviceDesc.Streams[0], "/dolittle.runtime.events.processing.Filters/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &filtersConnectClient{stream}
	return x, nil
}

type Filters_ConnectClient interface {
	Send(*FiltersClientToRuntimeMessage) error
	Recv() (*FilterRuntimeToClientMessage, error)
	grpc.ClientStream
}

type filtersConnectClient struct {
	grpc.ClientStream
}

func (x *filtersConnectClient) Send(m *FiltersClientToRuntimeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *filtersConnectClient) Recv() (*FilterRuntimeToClientMessage, error) {
	m := new(FilterRuntimeToClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FiltersServer is the server API for Filters service.
type FiltersServer interface {
	Connect(Filters_ConnectServer) error
}

// UnimplementedFiltersServer can be embedded to have forward compatible implementations.
type UnimplementedFiltersServer struct {
}

func (*UnimplementedFiltersServer) Connect(srv Filters_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func RegisterFiltersServer(s *grpc.Server, srv FiltersServer) {
	s.RegisterService(&_Filters_serviceDesc, srv)
}

func _Filters_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FiltersServer).Connect(&filtersConnectServer{stream})
}

type Filters_ConnectServer interface {
	Send(*FilterRuntimeToClientMessage) error
	Recv() (*FiltersClientToRuntimeMessage, error)
	grpc.ServerStream
}

type filtersConnectServer struct {
	grpc.ServerStream
}

func (x *filtersConnectServer) Send(m *FilterRuntimeToClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *filtersConnectServer) Recv() (*FiltersClientToRuntimeMessage, error) {
	m := new(FiltersClientToRuntimeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Filters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dolittle.runtime.events.processing.Filters",
	HandlerType: (*FiltersServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Filters_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Runtime/Events.Processing/Filters.proto",
}
