// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Runtime/Events.Processing/Processors.proto

package processing

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	protobuf "go.dolittle.io/chaostests/contracts/protobuf"
	services "go.dolittle.io/chaostests/contracts/services"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProcessorFailure struct {
	Reason               string             `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Retry                bool               `protobuf:"varint,2,opt,name=retry,proto3" json:"retry,omitempty"`
	RetryTimeout         *duration.Duration `protobuf:"bytes,3,opt,name=retryTimeout,proto3" json:"retryTimeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProcessorFailure) Reset()         { *m = ProcessorFailure{} }
func (m *ProcessorFailure) String() string { return proto.CompactTextString(m) }
func (*ProcessorFailure) ProtoMessage()    {}
func (*ProcessorFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{0}
}

func (m *ProcessorFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorFailure.Unmarshal(m, b)
}
func (m *ProcessorFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorFailure.Marshal(b, m, deterministic)
}
func (m *ProcessorFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorFailure.Merge(m, src)
}
func (m *ProcessorFailure) XXX_Size() int {
	return xxx_messageInfo_ProcessorFailure.Size(m)
}
func (m *ProcessorFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorFailure.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorFailure proto.InternalMessageInfo

func (m *ProcessorFailure) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *ProcessorFailure) GetRetry() bool {
	if m != nil {
		return m.Retry
	}
	return false
}

func (m *ProcessorFailure) GetRetryTimeout() *duration.Duration {
	if m != nil {
		return m.RetryTimeout
	}
	return nil
}

type RetryProcessingState struct {
	FailureReason        string   `protobuf:"bytes,1,opt,name=failureReason,proto3" json:"failureReason,omitempty"`
	RetryCount           uint32   `protobuf:"varint,2,opt,name=retryCount,proto3" json:"retryCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetryProcessingState) Reset()         { *m = RetryProcessingState{} }
func (m *RetryProcessingState) String() string { return proto.CompactTextString(m) }
func (*RetryProcessingState) ProtoMessage()    {}
func (*RetryProcessingState) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{1}
}

func (m *RetryProcessingState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetryProcessingState.Unmarshal(m, b)
}
func (m *RetryProcessingState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetryProcessingState.Marshal(b, m, deterministic)
}
func (m *RetryProcessingState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetryProcessingState.Merge(m, src)
}
func (m *RetryProcessingState) XXX_Size() int {
	return xxx_messageInfo_RetryProcessingState.Size(m)
}
func (m *RetryProcessingState) XXX_DiscardUnknown() {
	xxx_messageInfo_RetryProcessingState.DiscardUnknown(m)
}

var xxx_messageInfo_RetryProcessingState proto.InternalMessageInfo

func (m *RetryProcessingState) GetFailureReason() string {
	if m != nil {
		return m.FailureReason
	}
	return ""
}

func (m *RetryProcessingState) GetRetryCount() uint32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

type ProcessorsRegistrationRequest struct {
	CallContext          *services.ReverseCallArgumentsContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	ScopeId              *protobuf.Uuid                        `protobuf:"bytes,2,opt,name=scopeId,proto3" json:"scopeId,omitempty"`
	ProcessorId          *protobuf.Uuid                        `protobuf:"bytes,3,opt,name=processorId,proto3" json:"processorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *ProcessorsRegistrationRequest) Reset()         { *m = ProcessorsRegistrationRequest{} }
func (m *ProcessorsRegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessorsRegistrationRequest) ProtoMessage()    {}
func (*ProcessorsRegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{2}
}

func (m *ProcessorsRegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorsRegistrationRequest.Unmarshal(m, b)
}
func (m *ProcessorsRegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorsRegistrationRequest.Marshal(b, m, deterministic)
}
func (m *ProcessorsRegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorsRegistrationRequest.Merge(m, src)
}
func (m *ProcessorsRegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessorsRegistrationRequest.Size(m)
}
func (m *ProcessorsRegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorsRegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorsRegistrationRequest proto.InternalMessageInfo

func (m *ProcessorsRegistrationRequest) GetCallContext() *services.ReverseCallArgumentsContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *ProcessorsRegistrationRequest) GetScopeId() *protobuf.Uuid {
	if m != nil {
		return m.ScopeId
	}
	return nil
}

func (m *ProcessorsRegistrationRequest) GetProcessorId() *protobuf.Uuid {
	if m != nil {
		return m.ProcessorId
	}
	return nil
}

type ProcessorResponse struct {
	CallContext          *services.ReverseCallResponseContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	Failure              *ProcessorFailure                    `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ProcessorResponse) Reset()         { *m = ProcessorResponse{} }
func (m *ProcessorResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessorResponse) ProtoMessage()    {}
func (*ProcessorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{3}
}

func (m *ProcessorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorResponse.Unmarshal(m, b)
}
func (m *ProcessorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorResponse.Marshal(b, m, deterministic)
}
func (m *ProcessorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorResponse.Merge(m, src)
}
func (m *ProcessorResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessorResponse.Size(m)
}
func (m *ProcessorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorResponse proto.InternalMessageInfo

func (m *ProcessorResponse) GetCallContext() *services.ReverseCallResponseContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *ProcessorResponse) GetFailure() *ProcessorFailure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type ProcessorsClientToRuntimeMessage struct {
	// Types that are valid to be assigned to Message:
	//	*ProcessorsClientToRuntimeMessage_RegistrationRequest
	//	*ProcessorsClientToRuntimeMessage_ProcessingResult
	Message              isProcessorsClientToRuntimeMessage_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *ProcessorsClientToRuntimeMessage) Reset()         { *m = ProcessorsClientToRuntimeMessage{} }
func (m *ProcessorsClientToRuntimeMessage) String() string { return proto.CompactTextString(m) }
func (*ProcessorsClientToRuntimeMessage) ProtoMessage()    {}
func (*ProcessorsClientToRuntimeMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{4}
}

func (m *ProcessorsClientToRuntimeMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorsClientToRuntimeMessage.Unmarshal(m, b)
}
func (m *ProcessorsClientToRuntimeMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorsClientToRuntimeMessage.Marshal(b, m, deterministic)
}
func (m *ProcessorsClientToRuntimeMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorsClientToRuntimeMessage.Merge(m, src)
}
func (m *ProcessorsClientToRuntimeMessage) XXX_Size() int {
	return xxx_messageInfo_ProcessorsClientToRuntimeMessage.Size(m)
}
func (m *ProcessorsClientToRuntimeMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorsClientToRuntimeMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorsClientToRuntimeMessage proto.InternalMessageInfo

type isProcessorsClientToRuntimeMessage_Message interface {
	isProcessorsClientToRuntimeMessage_Message()
}

type ProcessorsClientToRuntimeMessage_RegistrationRequest struct {
	RegistrationRequest *ProcessorsRegistrationRequest `protobuf:"bytes,1,opt,name=registrationRequest,proto3,oneof"`
}

type ProcessorsClientToRuntimeMessage_ProcessingResult struct {
	ProcessingResult *ProcessorResponse `protobuf:"bytes,2,opt,name=processingResult,proto3,oneof"`
}

func (*ProcessorsClientToRuntimeMessage_RegistrationRequest) isProcessorsClientToRuntimeMessage_Message() {
}

func (*ProcessorsClientToRuntimeMessage_ProcessingResult) isProcessorsClientToRuntimeMessage_Message() {
}

func (m *ProcessorsClientToRuntimeMessage) GetMessage() isProcessorsClientToRuntimeMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ProcessorsClientToRuntimeMessage) GetRegistrationRequest() *ProcessorsRegistrationRequest {
	if x, ok := m.GetMessage().(*ProcessorsClientToRuntimeMessage_RegistrationRequest); ok {
		return x.RegistrationRequest
	}
	return nil
}

func (m *ProcessorsClientToRuntimeMessage) GetProcessingResult() *ProcessorResponse {
	if x, ok := m.GetMessage().(*ProcessorsClientToRuntimeMessage_ProcessingResult); ok {
		return x.ProcessingResult
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProcessorsClientToRuntimeMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProcessorsClientToRuntimeMessage_RegistrationRequest)(nil),
		(*ProcessorsClientToRuntimeMessage_ProcessingResult)(nil),
	}
}

type ProcessorRegistrationResponse struct {
	Failure              *protobuf.Failure `protobuf:"bytes,1,opt,name=failure,proto3" json:"failure,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessorRegistrationResponse) Reset()         { *m = ProcessorRegistrationResponse{} }
func (m *ProcessorRegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*ProcessorRegistrationResponse) ProtoMessage()    {}
func (*ProcessorRegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{5}
}

func (m *ProcessorRegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorRegistrationResponse.Unmarshal(m, b)
}
func (m *ProcessorRegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorRegistrationResponse.Marshal(b, m, deterministic)
}
func (m *ProcessorRegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorRegistrationResponse.Merge(m, src)
}
func (m *ProcessorRegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_ProcessorRegistrationResponse.Size(m)
}
func (m *ProcessorRegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorRegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorRegistrationResponse proto.InternalMessageInfo

func (m *ProcessorRegistrationResponse) GetFailure() *protobuf.Failure {
	if m != nil {
		return m.Failure
	}
	return nil
}

type ProcessEventRequest struct {
	CallContext          *services.ReverseCallRequestContext `protobuf:"bytes,1,opt,name=callContext,proto3" json:"callContext,omitempty"`
	Event                *StreamEvent                        `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	RetryProcessingState *RetryProcessingState               `protobuf:"bytes,3,opt,name=retryProcessingState,proto3" json:"retryProcessingState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ProcessEventRequest) Reset()         { *m = ProcessEventRequest{} }
func (m *ProcessEventRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessEventRequest) ProtoMessage()    {}
func (*ProcessEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{6}
}

func (m *ProcessEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessEventRequest.Unmarshal(m, b)
}
func (m *ProcessEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessEventRequest.Marshal(b, m, deterministic)
}
func (m *ProcessEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessEventRequest.Merge(m, src)
}
func (m *ProcessEventRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessEventRequest.Size(m)
}
func (m *ProcessEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessEventRequest proto.InternalMessageInfo

func (m *ProcessEventRequest) GetCallContext() *services.ReverseCallRequestContext {
	if m != nil {
		return m.CallContext
	}
	return nil
}

func (m *ProcessEventRequest) GetEvent() *StreamEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *ProcessEventRequest) GetRetryProcessingState() *RetryProcessingState {
	if m != nil {
		return m.RetryProcessingState
	}
	return nil
}

type ProcessorRuntimeToClientMessage struct {
	// Types that are valid to be assigned to Message:
	//	*ProcessorRuntimeToClientMessage_RegistrationResponse
	//	*ProcessorRuntimeToClientMessage_HandleRequest
	Message              isProcessorRuntimeToClientMessage_Message `protobuf_oneof:"Message"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *ProcessorRuntimeToClientMessage) Reset()         { *m = ProcessorRuntimeToClientMessage{} }
func (m *ProcessorRuntimeToClientMessage) String() string { return proto.CompactTextString(m) }
func (*ProcessorRuntimeToClientMessage) ProtoMessage()    {}
func (*ProcessorRuntimeToClientMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_af85d77977561970, []int{7}
}

func (m *ProcessorRuntimeToClientMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessorRuntimeToClientMessage.Unmarshal(m, b)
}
func (m *ProcessorRuntimeToClientMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessorRuntimeToClientMessage.Marshal(b, m, deterministic)
}
func (m *ProcessorRuntimeToClientMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessorRuntimeToClientMessage.Merge(m, src)
}
func (m *ProcessorRuntimeToClientMessage) XXX_Size() int {
	return xxx_messageInfo_ProcessorRuntimeToClientMessage.Size(m)
}
func (m *ProcessorRuntimeToClientMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessorRuntimeToClientMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessorRuntimeToClientMessage proto.InternalMessageInfo

type isProcessorRuntimeToClientMessage_Message interface {
	isProcessorRuntimeToClientMessage_Message()
}

type ProcessorRuntimeToClientMessage_RegistrationResponse struct {
	RegistrationResponse *ProcessorRegistrationResponse `protobuf:"bytes,1,opt,name=registrationResponse,proto3,oneof"`
}

type ProcessorRuntimeToClientMessage_HandleRequest struct {
	HandleRequest *ProcessEventRequest `protobuf:"bytes,2,opt,name=handleRequest,proto3,oneof"`
}

func (*ProcessorRuntimeToClientMessage_RegistrationResponse) isProcessorRuntimeToClientMessage_Message() {
}

func (*ProcessorRuntimeToClientMessage_HandleRequest) isProcessorRuntimeToClientMessage_Message() {}

func (m *ProcessorRuntimeToClientMessage) GetMessage() isProcessorRuntimeToClientMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *ProcessorRuntimeToClientMessage) GetRegistrationResponse() *ProcessorRegistrationResponse {
	if x, ok := m.GetMessage().(*ProcessorRuntimeToClientMessage_RegistrationResponse); ok {
		return x.RegistrationResponse
	}
	return nil
}

func (m *ProcessorRuntimeToClientMessage) GetHandleRequest() *ProcessEventRequest {
	if x, ok := m.GetMessage().(*ProcessorRuntimeToClientMessage_HandleRequest); ok {
		return x.HandleRequest
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ProcessorRuntimeToClientMessage) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ProcessorRuntimeToClientMessage_RegistrationResponse)(nil),
		(*ProcessorRuntimeToClientMessage_HandleRequest)(nil),
	}
}

func init() {
	proto.RegisterType((*ProcessorFailure)(nil), "dolittle.runtime.events.processing.ProcessorFailure")
	proto.RegisterType((*RetryProcessingState)(nil), "dolittle.runtime.events.processing.RetryProcessingState")
	proto.RegisterType((*ProcessorsRegistrationRequest)(nil), "dolittle.runtime.events.processing.ProcessorsRegistrationRequest")
	proto.RegisterType((*ProcessorResponse)(nil), "dolittle.runtime.events.processing.ProcessorResponse")
	proto.RegisterType((*ProcessorsClientToRuntimeMessage)(nil), "dolittle.runtime.events.processing.ProcessorsClientToRuntimeMessage")
	proto.RegisterType((*ProcessorRegistrationResponse)(nil), "dolittle.runtime.events.processing.ProcessorRegistrationResponse")
	proto.RegisterType((*ProcessEventRequest)(nil), "dolittle.runtime.events.processing.ProcessEventRequest")
	proto.RegisterType((*ProcessorRuntimeToClientMessage)(nil), "dolittle.runtime.events.processing.ProcessorRuntimeToClientMessage")
}

func init() {
	proto.RegisterFile("Runtime/Events.Processing/Processors.proto", fileDescriptor_af85d77977561970)
}

var fileDescriptor_af85d77977561970 = []byte{
	// 716 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x55, 0xcd, 0x6e, 0xd3, 0x4a,
	0x14, 0x8e, 0x73, 0xd5, 0xe6, 0xf6, 0xe4, 0x56, 0xea, 0x9d, 0x56, 0xf7, 0x96, 0x48, 0x94, 0xc8,
	0xb0, 0x88, 0xa0, 0x8c, 0x21, 0x14, 0x01, 0x8b, 0x2e, 0xda, 0xb4, 0x55, 0xba, 0xa0, 0x54, 0xd3,
	0x76, 0x83, 0x90, 0x90, 0x6b, 0x9f, 0xba, 0x96, 0x9c, 0x99, 0x30, 0x33, 0x2e, 0xb0, 0x62, 0x87,
	0xc4, 0x1b, 0x20, 0x5e, 0x00, 0x89, 0x35, 0xef, 0xc3, 0xab, 0xa0, 0xd8, 0xe3, 0xd8, 0x21, 0x53,
	0xda, 0xb0, 0xb3, 0x9d, 0x73, 0xbe, 0x73, 0xbe, 0x9f, 0x99, 0xc0, 0x5d, 0x96, 0x72, 0x1d, 0x0f,
	0xd0, 0xdb, 0xbd, 0x40, 0xae, 0x15, 0x3d, 0x94, 0x22, 0x40, 0xa5, 0x62, 0x1e, 0x79, 0xe6, 0x51,
	0x48, 0x45, 0x87, 0x52, 0x68, 0x41, 0xdc, 0x50, 0x24, 0xb1, 0xd6, 0x09, 0x52, 0x99, 0x37, 0x51,
	0xcc, 0x9b, 0x86, 0xe3, 0xa6, 0xd6, 0xed, 0xbd, 0x94, 0x87, 0xfe, 0x00, 0xb9, 0xf6, 0x13, 0x35,
	0x82, 0xd0, 0xe2, 0x34, 0x3d, 0xf3, 0xf6, 0xfc, 0x38, 0x49, 0x25, 0xe6, 0x40, 0xad, 0xb6, 0xbd,
	0xe8, 0x24, 0x8d, 0x43, 0x53, 0x41, 0x27, 0x2a, 0x8e, 0x50, 0x5e, 0xc4, 0x01, 0x2a, 0x8f, 0xe1,
	0x05, 0x4a, 0x85, 0x3d, 0x3f, 0x49, 0x7a, 0x82, 0x6b, 0x7c, 0xa7, 0x4d, 0xfd, 0xbd, 0xcb, 0x69,
	0x1c, 0x69, 0x89, 0xfe, 0x20, 0xfb, 0x6e, 0x8a, 0xd7, 0x22, 0x21, 0xa2, 0x04, 0xbd, 0x61, 0x31,
	0x38, 0x4c, 0xa5, 0xaf, 0x63, 0xc1, 0xf3, 0xdf, 0xdd, 0x0f, 0xb0, 0x34, 0xe6, 0x6e, 0x16, 0x27,
	0xff, 0xc1, 0xbc, 0x44, 0x5f, 0x09, 0xbe, 0xea, 0xb4, 0x9d, 0xce, 0x02, 0x33, 0x6f, 0x64, 0x05,
	0xe6, 0x24, 0x6a, 0xf9, 0x7e, 0xb5, 0xde, 0x76, 0x3a, 0x7f, 0xb3, 0xfc, 0x85, 0x6c, 0xc2, 0x3f,
	0xd9, 0xc3, 0x71, 0x3c, 0x40, 0x91, 0xea, 0xd5, 0xbf, 0xda, 0x4e, 0xa7, 0xd9, 0xbd, 0x41, 0xf3,
	0xc1, 0xb4, 0x18, 0x4c, 0x77, 0xcc, 0x60, 0x36, 0x51, 0xee, 0xbe, 0x82, 0x15, 0x36, 0x7a, 0x2f,
	0x59, 0x1c, 0x69, 0x5f, 0x23, 0xb9, 0x03, 0x8b, 0x67, 0xf9, 0x3e, 0xac, 0xba, 0xcb, 0xe4, 0x47,
	0xb2, 0x06, 0x90, 0xa1, 0xf5, 0x44, 0xca, 0x75, 0xb6, 0xd7, 0x22, 0xab, 0x7c, 0x71, 0x7f, 0x38,
	0x70, 0xb3, 0xf4, 0x96, 0x61, 0x14, 0x2b, 0x6d, 0xd6, 0xc0, 0x37, 0x29, 0x2a, 0x4d, 0x0e, 0xa1,
	0x19, 0x94, 0x12, 0x67, 0x53, 0x9a, 0x5d, 0x4a, 0xc7, 0xf6, 0x2b, 0xe3, 0x07, 0xad, 0xf8, 0xb1,
	0x25, 0xa3, 0x74, 0xe4, 0x97, 0x32, 0x5d, 0xac, 0x0a, 0x41, 0x1e, 0x42, 0x43, 0x05, 0x62, 0x88,
	0xfb, 0x61, 0xb6, 0x50, 0xb3, 0xfb, 0x7f, 0x89, 0x36, 0x56, 0x63, 0xe4, 0x3f, 0x2b, 0xea, 0xc8,
	0x33, 0x68, 0x0e, 0x8b, 0x2d, 0xf7, 0x43, 0x23, 0xe1, 0xa5, 0x6d, 0xd5, 0x5a, 0xf7, 0xbb, 0x03,
	0xff, 0x8e, 0x19, 0x32, 0x54, 0x43, 0xc1, 0x15, 0x92, 0x17, 0x36, 0x56, 0xf7, 0x7f, 0xcf, 0xaa,
	0x68, 0xb6, 0x92, 0x3a, 0x80, 0x86, 0x51, 0xde, 0x90, 0xda, 0xa0, 0x57, 0x9f, 0x10, 0xfa, 0x6b,
	0xb4, 0x58, 0x01, 0xe2, 0x7e, 0xaa, 0x43, 0xbb, 0x34, 0xa6, 0x97, 0xc4, 0xc8, 0xf5, 0xb1, 0x30,
	0xc9, 0x7e, 0x8e, 0x4a, 0xf9, 0x11, 0x92, 0x14, 0x96, 0xe5, 0xb4, 0x65, 0x86, 0xcd, 0xd6, 0x4c,
	0x0b, 0xd8, 0xbc, 0xef, 0xd7, 0x98, 0x0d, 0x9f, 0x04, 0xb0, 0x54, 0x42, 0x30, 0x54, 0x69, 0xa2,
	0x0d, 0xe9, 0xc7, 0x33, 0xcd, 0x2c, 0x04, 0xed, 0xd7, 0xd8, 0x14, 0xe0, 0xf6, 0x02, 0x34, 0x0c,
	0x4d, 0xf7, 0xa4, 0x92, 0xd1, 0xc9, 0x35, 0x8d, 0x9b, 0x1b, 0xa5, 0xf8, 0x39, 0xf7, 0x96, 0x25,
	0x1a, 0x53, 0x12, 0x7f, 0xa9, 0xc3, 0xb2, 0xc1, 0xcd, 0x6e, 0x84, 0x82, 0xde, 0x81, 0x2d, 0x1b,
	0xeb, 0x57, 0x65, 0x23, 0xeb, 0xb5, 0x46, 0x63, 0x17, 0xe6, 0x32, 0x11, 0x8c, 0x46, 0xde, 0x75,
	0x34, 0xaa, 0x5c, 0x54, 0x2c, 0xef, 0x26, 0x09, 0xac, 0x48, 0xcb, 0x45, 0x60, 0x0e, 0xc3, 0xd3,
	0xeb, 0xa0, 0xda, 0x2e, 0x12, 0x66, 0x45, 0x75, 0x3f, 0xd6, 0xe1, 0x56, 0x29, 0x7a, 0x8e, 0x78,
	0x2c, 0xf2, 0x1c, 0x16, 0xf1, 0x7b, 0x3b, 0xda, 0x68, 0xda, 0x8e, 0x3f, 0xca, 0x9f, 0xcd, 0xd7,
	0x7e, 0x8d, 0x59, 0x07, 0x90, 0xd7, 0xb0, 0x78, 0xee, 0xf3, 0x30, 0xc1, 0x22, 0xf1, 0xb9, 0xb2,
	0x4f, 0x66, 0x98, 0x58, 0x75, 0xbc, 0x5f, 0x63, 0x93, 0x78, 0x95, 0xf0, 0x75, 0xbf, 0x3a, 0x00,
	0xe5, 0x29, 0x21, 0x9f, 0x1d, 0x68, 0xf4, 0x04, 0xe7, 0x18, 0x68, 0xb2, 0x33, 0xdb, 0x09, 0xb3,
	0x1f, 0xe2, 0x56, 0x6f, 0x36, 0x9d, 0xac, 0x56, 0x74, 0x9c, 0x07, 0xce, 0x36, 0x7f, 0xb9, 0x19,
	0x89, 0x12, 0x2c, 0x16, 0x5e, 0x70, 0xee, 0x0b, 0xa5, 0x51, 0x69, 0xe5, 0x05, 0x82, 0x6b, 0xe9,
	0x07, 0x5a, 0x79, 0x66, 0x88, 0x97, 0x0f, 0xf1, 0xca, 0x21, 0xdf, 0xea, 0xeb, 0x3b, 0x45, 0xb3,
	0x19, 0x43, 0xa7, 0xfe, 0x42, 0x69, 0xaf, 0x00, 0x3a, 0x9d, 0xcf, 0x8e, 0xd6, 0xa3, 0x9f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x2e, 0x38, 0x09, 0x34, 0x37, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProcessorsClient is the client API for Processors service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProcessorsClient interface {
	Connect(ctx context.Context, opts ...grpc.CallOption) (Processors_ConnectClient, error)
}

type processorsClient struct {
	cc *grpc.ClientConn
}

func NewProcessorsClient(cc *grpc.ClientConn) ProcessorsClient {
	return &processorsClient{cc}
}

func (c *processorsClient) Connect(ctx context.Context, opts ...grpc.CallOption) (Processors_ConnectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Processors_serviceDesc.Streams[0], "/dolittle.runtime.events.processing.Processors/Connect", opts...)
	if err != nil {
		return nil, err
	}
	x := &processorsConnectClient{stream}
	return x, nil
}

type Processors_ConnectClient interface {
	Send(*ProcessorsClientToRuntimeMessage) error
	Recv() (*ProcessorRuntimeToClientMessage, error)
	grpc.ClientStream
}

type processorsConnectClient struct {
	grpc.ClientStream
}

func (x *processorsConnectClient) Send(m *ProcessorsClientToRuntimeMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *processorsConnectClient) Recv() (*ProcessorRuntimeToClientMessage, error) {
	m := new(ProcessorRuntimeToClientMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProcessorsServer is the server API for Processors service.
type ProcessorsServer interface {
	Connect(Processors_ConnectServer) error
}

// UnimplementedProcessorsServer can be embedded to have forward compatible implementations.
type UnimplementedProcessorsServer struct {
}

func (*UnimplementedProcessorsServer) Connect(srv Processors_ConnectServer) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func RegisterProcessorsServer(s *grpc.Server, srv ProcessorsServer) {
	s.RegisterService(&_Processors_serviceDesc, srv)
}

func _Processors_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ProcessorsServer).Connect(&processorsConnectServer{stream})
}

type Processors_ConnectServer interface {
	Send(*ProcessorRuntimeToClientMessage) error
	Recv() (*ProcessorsClientToRuntimeMessage, error)
	grpc.ServerStream
}

type processorsConnectServer struct {
	grpc.ServerStream
}

func (x *processorsConnectServer) Send(m *ProcessorRuntimeToClientMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *processorsConnectServer) Recv() (*ProcessorsClientToRuntimeMessage, error) {
	m := new(ProcessorsClientToRuntimeMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Processors_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dolittle.runtime.events.processing.Processors",
	HandlerType: (*ProcessorsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _Processors_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Runtime/Events.Processing/Processors.proto",
}
