// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Fundamentals/Services/ReverseCallContext.proto

package services

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	execution "go.dolittle.io/chaostests/contracts/execution"
	protobuf "go.dolittle.io/chaostests/contracts/protobuf"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReverseCallArgumentsContext struct {
	ExecutionContext     *execution.ExecutionContext `protobuf:"bytes,1,opt,name=executionContext,proto3" json:"executionContext,omitempty"`
	HeadId               *protobuf.Uuid              `protobuf:"bytes,2,opt,name=headId,proto3" json:"headId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReverseCallArgumentsContext) Reset()         { *m = ReverseCallArgumentsContext{} }
func (m *ReverseCallArgumentsContext) String() string { return proto.CompactTextString(m) }
func (*ReverseCallArgumentsContext) ProtoMessage()    {}
func (*ReverseCallArgumentsContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_06c3b552c66265a5, []int{0}
}

func (m *ReverseCallArgumentsContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseCallArgumentsContext.Unmarshal(m, b)
}
func (m *ReverseCallArgumentsContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseCallArgumentsContext.Marshal(b, m, deterministic)
}
func (m *ReverseCallArgumentsContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseCallArgumentsContext.Merge(m, src)
}
func (m *ReverseCallArgumentsContext) XXX_Size() int {
	return xxx_messageInfo_ReverseCallArgumentsContext.Size(m)
}
func (m *ReverseCallArgumentsContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseCallArgumentsContext.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseCallArgumentsContext proto.InternalMessageInfo

func (m *ReverseCallArgumentsContext) GetExecutionContext() *execution.ExecutionContext {
	if m != nil {
		return m.ExecutionContext
	}
	return nil
}

func (m *ReverseCallArgumentsContext) GetHeadId() *protobuf.Uuid {
	if m != nil {
		return m.HeadId
	}
	return nil
}

type ReverseCallRequestContext struct {
	CallId               *protobuf.Uuid              `protobuf:"bytes,1,opt,name=callId,proto3" json:"callId,omitempty"`
	ExecutionContext     *execution.ExecutionContext `protobuf:"bytes,2,opt,name=executionContext,proto3" json:"executionContext,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *ReverseCallRequestContext) Reset()         { *m = ReverseCallRequestContext{} }
func (m *ReverseCallRequestContext) String() string { return proto.CompactTextString(m) }
func (*ReverseCallRequestContext) ProtoMessage()    {}
func (*ReverseCallRequestContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_06c3b552c66265a5, []int{1}
}

func (m *ReverseCallRequestContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseCallRequestContext.Unmarshal(m, b)
}
func (m *ReverseCallRequestContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseCallRequestContext.Marshal(b, m, deterministic)
}
func (m *ReverseCallRequestContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseCallRequestContext.Merge(m, src)
}
func (m *ReverseCallRequestContext) XXX_Size() int {
	return xxx_messageInfo_ReverseCallRequestContext.Size(m)
}
func (m *ReverseCallRequestContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseCallRequestContext.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseCallRequestContext proto.InternalMessageInfo

func (m *ReverseCallRequestContext) GetCallId() *protobuf.Uuid {
	if m != nil {
		return m.CallId
	}
	return nil
}

func (m *ReverseCallRequestContext) GetExecutionContext() *execution.ExecutionContext {
	if m != nil {
		return m.ExecutionContext
	}
	return nil
}

type ReverseCallResponseContext struct {
	CallId               *protobuf.Uuid `protobuf:"bytes,1,opt,name=callId,proto3" json:"callId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReverseCallResponseContext) Reset()         { *m = ReverseCallResponseContext{} }
func (m *ReverseCallResponseContext) String() string { return proto.CompactTextString(m) }
func (*ReverseCallResponseContext) ProtoMessage()    {}
func (*ReverseCallResponseContext) Descriptor() ([]byte, []int) {
	return fileDescriptor_06c3b552c66265a5, []int{2}
}

func (m *ReverseCallResponseContext) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseCallResponseContext.Unmarshal(m, b)
}
func (m *ReverseCallResponseContext) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseCallResponseContext.Marshal(b, m, deterministic)
}
func (m *ReverseCallResponseContext) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseCallResponseContext.Merge(m, src)
}
func (m *ReverseCallResponseContext) XXX_Size() int {
	return xxx_messageInfo_ReverseCallResponseContext.Size(m)
}
func (m *ReverseCallResponseContext) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseCallResponseContext.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseCallResponseContext proto.InternalMessageInfo

func (m *ReverseCallResponseContext) GetCallId() *protobuf.Uuid {
	if m != nil {
		return m.CallId
	}
	return nil
}

func init() {
	proto.RegisterType((*ReverseCallArgumentsContext)(nil), "dolittle.services.ReverseCallArgumentsContext")
	proto.RegisterType((*ReverseCallRequestContext)(nil), "dolittle.services.ReverseCallRequestContext")
	proto.RegisterType((*ReverseCallResponseContext)(nil), "dolittle.services.ReverseCallResponseContext")
}

func init() {
	proto.RegisterFile("Fundamentals/Services/ReverseCallContext.proto", fileDescriptor_06c3b552c66265a5)
}

var fileDescriptor_06c3b552c66265a5 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x40, 0x95, 0x0c, 0x1d, 0xcc, 0x02, 0x59, 0x28, 0xe9, 0x52, 0x45, 0x0c, 0x0c, 0x60, 0x4b,
	0xf0, 0x05, 0x10, 0x40, 0xaa, 0x04, 0x52, 0x15, 0xc4, 0xc2, 0xe6, 0xda, 0x47, 0x1b, 0xc9, 0xd8,
	0x21, 0x77, 0xae, 0xfa, 0x35, 0x88, 0x99, 0xaf, 0x44, 0x69, 0x93, 0x26, 0x29, 0xb0, 0xd0, 0xcd,
	0xb2, 0x9e, 0x9f, 0xdf, 0x49, 0xc7, 0xf8, 0xbd, 0xb7, 0x5a, 0xbe, 0x81, 0x25, 0x69, 0x50, 0x3c,
	0x41, 0xb9, 0xcc, 0x15, 0xa0, 0xc8, 0x60, 0x09, 0x25, 0x42, 0x2a, 0x8d, 0x49, 0x9d, 0x25, 0x58,
	0x11, 0x2f, 0x4a, 0x47, 0x2e, 0x3a, 0xd2, 0xce, 0xe4, 0x44, 0x06, 0x38, 0xd6, 0x6c, 0x7c, 0xd1,
	0x53, 0xdc, 0xad, 0x40, 0x79, 0xca, 0x9d, 0x6d, 0x4f, 0x3d, 0x43, 0x3c, 0xee, 0xe1, 0xd3, 0xea,
	0x6e, 0xe6, 0x5f, 0xc5, 0xb3, 0xcf, 0xf5, 0x86, 0x48, 0x3e, 0x03, 0x36, 0xea, 0x04, 0x5c, 0x97,
	0x73, 0x5f, 0xe1, 0x58, 0x7b, 0xa2, 0x29, 0x3b, 0x84, 0x1d, 0xf7, 0x30, 0x18, 0x07, 0x67, 0x07,
	0x97, 0xa7, 0x7c, 0x9b, 0xb7, 0x25, 0xf8, 0x6e, 0x47, 0xf6, 0xe3, 0x75, 0x24, 0xd8, 0x60, 0x01,
	0x52, 0x4f, 0xf4, 0x30, 0x5c, 0x7b, 0x8e, 0x5b, 0x4f, 0x51, 0x07, 0xf2, 0x2a, 0x30, 0xab, 0xb1,
	0xe4, 0x23, 0x60, 0x27, 0x9d, 0xc4, 0x0c, 0xde, 0x3d, 0x20, 0x75, 0x74, 0x4a, 0x1a, 0x33, 0xd1,
	0x75, 0xd6, 0xdf, 0xba, 0x0d, 0xf6, 0xeb, 0x44, 0xe1, 0x3e, 0x13, 0x25, 0x8f, 0x2c, 0xee, 0xf5,
	0x61, 0xe1, 0x2c, 0xc2, 0x7f, 0x03, 0x6f, 0x1e, 0x5e, 0xce, 0xe7, 0xae, 0x85, 0x72, 0x27, 0xd4,
	0x42, 0x3a, 0x24, 0x40, 0x42, 0xa1, 0x9c, 0xa5, 0x52, 0x2a, 0x42, 0xd1, 0xec, 0xc4, 0x57, 0x38,
	0xba, 0x6d, 0xd8, 0x66, 0xa7, 0x78, 0xda, 0x60, 0xb3, 0xc1, 0xfa, 0x93, 0xab, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa3, 0x30, 0xd1, 0xa7, 0x7d, 0x02, 0x00, 0x00,
}
